name: apex
version: 1.0.0+1
publish_to: none
description: DevitCity Flutter App.
environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.10+1
  flutter_easyloading: ^3.0.5
  smooth_page_indicator: ^1.2.0+3
  camera: ^0.10.5

  shimmer: ^3.0.0
  image_picker: ^0.8.7+5
  dio: ^5.9.0

  http: ^1.0.0
  open_settings_plus: ^0.4.0
  flutter_secure_storage: ^9.2.4
  logger: ^2.5.0
  connectivity_plus: ^6.1.4
  shared_preferences: ^2.5.3
  intl: ^0.20.2

  firebase_core: ^3.14.0
  firebase_auth: ^5.5.1
  flutter_local_notifications: ^19.2.1
  flutter_native_splash: ^2.4.7

  url_launcher: ^6.2.5
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.4.1
  lucide_icons_flutter: ^3.1.6
  flutter_advanced_drawer: ^1.5.0
  flutter_map: ^6.0.0
  latlong2: ^0.9.0

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/icons/nav/

flutter_native_splash:
  color: "#0B0B0C"
  image: assets/images/logo.png
